CREATE TABLE public.organizacoes (
                                     id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     nome varchar(255) NOT NULL,
                                     CONSTRAINT organizacoes_pkey PRIMARY KEY (id),
                                     CONSTRAINT uk_12ajpu96i8d0i7ocqnd11hlgh UNIQUE (nome)
);
INSERT INTO organizacoes (nome) VALUES ('Sequencial');
INSERT INTO organizacoes (nome) VALUES ('Fibonatti');
INSERT INTO organizacoes (nome) VALUES ('T-Shirt');